#ifndef MICROS_IPC_ABI_H
#define MICROS_IPC_ABI_H

enum micros_ipc_abi_result {
    MICROS_IPC_ABI_OK = 0,
    MICROS_IPC_ABI_ARGUMENT = -1,
    MICROS_IPC_ABI_DEAD_ENDPOINT = -2,
    MICROS_IPC_ABI_UNAUTHORIZED = -3,
    MICROS_IPC_ABI_STATE = -4,
    MICROS_IPC_ABI_DEADLOCK = -5,
    MICROS_IPC_ABI_MESSAGE_FAULT = -6,
    MICROS_IPC_ABI_REPLY_TOKEN = -7,
    MICROS_IPC_ABI_REPLY_TOKEN_EXHAUSTED = -8,
    MICROS_IPC_ABI_ENDPOINT_CLOSING = -9,
};

#endif
