#ifndef MICROS_IPC_ABI_H
#define MICROS_IPC_ABI_H

#include <stdbool.h>
#include <stdint.h>

#include "micros/ipc.h"
#include "micros/syscall_abi.h"

enum micros_ipc_abi_operation {
    MICROS_IPC_ABI_SEND = MICROS_SYSCALL_ABI_SEND,
    MICROS_IPC_ABI_RECEIVE = MICROS_SYSCALL_ABI_RECEIVE,
    MICROS_IPC_ABI_CALL = MICROS_SYSCALL_ABI_CALL,
    MICROS_IPC_ABI_REPLY = MICROS_SYSCALL_ABI_REPLY,
    MICROS_IPC_ABI_REPLY_RECEIVE =
        MICROS_SYSCALL_ABI_REPLY_RECEIVE,
    MICROS_IPC_ABI_NOTIFY = MICROS_SYSCALL_ABI_NOTIFY,
};

enum micros_ipc_abi_result {
    MICROS_IPC_ABI_OK = MICROS_SYSCALL_ABI_OK,
    MICROS_IPC_ABI_ARGUMENT = MICROS_SYSCALL_ABI_ARGUMENT,
    MICROS_IPC_ABI_DEAD_ENDPOINT =
        MICROS_SYSCALL_ABI_DEAD_ENDPOINT,
    MICROS_IPC_ABI_UNAUTHORIZED =
        MICROS_SYSCALL_ABI_UNAUTHORIZED,
    MICROS_IPC_ABI_STATE = MICROS_SYSCALL_ABI_STATE,
    MICROS_IPC_ABI_DEADLOCK = MICROS_SYSCALL_ABI_DEADLOCK,
    MICROS_IPC_ABI_MESSAGE_FAULT =
        MICROS_SYSCALL_ABI_MEMORY_FAULT,
    MICROS_IPC_ABI_REPLY_TOKEN =
        MICROS_SYSCALL_ABI_REPLY_TOKEN,
    MICROS_IPC_ABI_REPLY_TOKEN_EXHAUSTED =
        MICROS_SYSCALL_ABI_REPLY_TOKEN_EXHAUSTED,
    MICROS_IPC_ABI_ENDPOINT_CLOSING =
        MICROS_SYSCALL_ABI_ENDPOINT_CLOSING,
};

bool micros_ipc_abi_map_error(
    enum micros_ipc_error error,
    uint64_t *result
);

#endif
