#ifndef MICROS_TTY_H
#define MICROS_TTY_H

#include <stdint.h>

enum {
    MICROS_TTY_PROTOCOL_VERSION = 1,
    MICROS_TTY_CONTROL_VERSION = 1,
    MICROS_TTY_MAPPING_VERSION = 1,
    MICROS_TTY_INPUT_CAPACITY = 256,
    MICROS_TTY_ECHO_CAPACITY = 256,
    MICROS_TTY_TRANSFER_MAX = 4096,
    MICROS_TTY_WRITE_CAPACITY = 4096,
    MICROS_TTY_SERVICE_ID = 4,
    MICROS_TTY_PROCESS_SLOT = 3,
    MICROS_TTY_UART_IRQ_SOURCE = 10,
};

#define MICROS_TTY_UART_VIRTUAL_BASE \
    UINT64_C(0x000000007fffe000)
#define MICROS_TTY_UART_PHYSICAL_BASE \
    UINT64_C(0x0000000010000000)
#define MICROS_TTY_UART_MAPPED_LENGTH UINT64_C(0x1000)

#define MICROS_TTY_MESSAGE_SUBMIT_READ UINT32_C(0x00020001)
#define MICROS_TTY_MESSAGE_SUBMIT_WRITE UINT32_C(0x00020002)
#define MICROS_TTY_MESSAGE_CANCEL UINT32_C(0x00020003)
#define MICROS_TTY_MESSAGE_COLLECT UINT32_C(0x00020004)
#define MICROS_TTY_MESSAGE_RESULT UINT32_C(0x00020005)

#define MICROS_TTY_EVENT_COMPLETION UINT64_C(0x1)
#define MICROS_TTY_EVENT_WRITABLE UINT64_C(0x2)

enum micros_tty_result {
    MICROS_TTY_RESULT_PENDING = -9,
    MICROS_TTY_RESULT_GRANT = -8,
    MICROS_TTY_RESULT_REQUEST = -7,
    MICROS_TTY_RESULT_BUSY = -6,
    MICROS_TTY_RESULT_STATE = -5,
    MICROS_TTY_RESULT_CALLER = -4,
    MICROS_TTY_RESULT_MALFORMED = -3,
    MICROS_TTY_RESULT_BAD_VERSION = -2,
    MICROS_TTY_RESULT_BAD_TYPE = -1,
    MICROS_TTY_RESULT_OK = 0,
};

enum micros_tty_control_command {
    MICROS_TTY_CONTROL_COMMIT = 1,
    MICROS_TTY_CONTROL_IRQ_COMPLETE = 2,
};

#endif
