#ifndef MICROS_VFS_H
#define MICROS_VFS_H

#include <stdint.h>

enum {
    MICROS_VFS_PROTOCOL_VERSION = 1,
    MICROS_VFS_TRANSFER_MAX = 4096,
    MICROS_VFS_PATH_MAX = 4096,
    MICROS_VFS_NAME_MAX = 60,
    MICROS_VFS_DIRECTORY_RECORD_SIZE = 80,
    MICROS_VFS_RESIDENT_PAGE_LIMIT = 64,
    MICROS_VFS_SERVICE_ID = 6,
    MICROS_VFS_PROCESS_SLOT = 5,
};

#define MICROS_VFS_ACCESS_READ UINT32_C(0x00000001)
#define MICROS_VFS_ACCESS_WRITE UINT32_C(0x00000002)
#define MICROS_VFS_ACCESS_DEFINED_MASK \
    (MICROS_VFS_ACCESS_READ | MICROS_VFS_ACCESS_WRITE)

#define MICROS_VFS_OPEN_READ UINT32_C(0x00000001)
#define MICROS_VFS_OPEN_WRITE UINT32_C(0x00000002)
#define MICROS_VFS_OPEN_CREATE UINT32_C(0x00000004)
#define MICROS_VFS_OPEN_EXCLUSIVE UINT32_C(0x00000008)
#define MICROS_VFS_OPEN_DIRECTORY UINT32_C(0x00000010)
#define MICROS_VFS_OPEN_DEFINED_MASK \
    ( \
        MICROS_VFS_OPEN_READ \
        | MICROS_VFS_OPEN_WRITE \
        | MICROS_VFS_OPEN_CREATE \
        | MICROS_VFS_OPEN_EXCLUSIVE \
        | MICROS_VFS_OPEN_DIRECTORY \
    )

#define MICROS_VFS_MESSAGE_OPEN UINT32_C(0x00040001)
#define MICROS_VFS_MESSAGE_CLOSE UINT32_C(0x00040002)
#define MICROS_VFS_MESSAGE_READ UINT32_C(0x00040003)
#define MICROS_VFS_MESSAGE_WRITE UINT32_C(0x00040004)
#define MICROS_VFS_MESSAGE_GETDENTS UINT32_C(0x00040005)
#define MICROS_VFS_MESSAGE_MKDIR UINT32_C(0x00040006)
#define MICROS_VFS_MESSAGE_CHDIR UINT32_C(0x00040007)
#define MICROS_VFS_MESSAGE_RESULT UINT32_C(0x00040008)

enum micros_vfs_result {
    MICROS_VFS_RESULT_RANGE = -15,
    MICROS_VFS_RESULT_GRANT = -14,
    MICROS_VFS_RESULT_NO_SPACE = -13,
    MICROS_VFS_RESULT_IS_DIRECTORY = -12,
    MICROS_VFS_RESULT_NOT_DIRECTORY = -11,
    MICROS_VFS_RESULT_EXISTS = -10,
    MICROS_VFS_RESULT_NOT_FOUND = -9,
    MICROS_VFS_RESULT_ACCESS = -8,
    MICROS_VFS_RESULT_DESCRIPTOR = -7,
    MICROS_VFS_RESULT_BUSY = -6,
    MICROS_VFS_RESULT_STATE = -5,
    MICROS_VFS_RESULT_CALLER = -4,
    MICROS_VFS_RESULT_MALFORMED = -3,
    MICROS_VFS_RESULT_BAD_VERSION = -2,
    MICROS_VFS_RESULT_BAD_TYPE = -1,
    MICROS_VFS_RESULT_OK = 0,
};

#endif
