#ifndef MICROS_TESTS_QEMU_BOOTSTRAP_PROTOCOL_H
#define MICROS_TESTS_QEMU_BOOTSTRAP_PROTOCOL_H

#include <stdint.h>

#include "micros/bootstrap.h"

enum {
    MICROS_BOOTSTRAP_TEST_LAUNCHER_SERVICE_ID = 1,
    MICROS_BOOTSTRAP_TEST_FIRST_SERVICE_ID = 2,
    MICROS_BOOTSTRAP_TEST_LAST_SERVICE_ID = 3,
    MICROS_BOOTSTRAP_TEST_SERVICE_COUNT = 3,
};

#define MICROS_BOOTSTRAP_TEST_READY_TIMEOUT UINT64_C(0x0000000000989680)
#define MICROS_BOOTSTRAP_TEST_SCHEDULER_INTERVAL \
    UINT64_C(0x00000000000186a0)

#endif
