#ifndef MICROS_TESTS_QEMU_PM_SERVICE_PROTOCOL_H
#define MICROS_TESTS_QEMU_PM_SERVICE_PROTOCOL_H

#include <stdint.h>

enum {
    MICROS_PM_TEST_LAUNCHER_SERVICE_ID = 1,
    MICROS_PM_TEST_VM_SERVICE_ID = 2,
    MICROS_PM_TEST_PM_SERVICE_ID = 3,
    MICROS_PM_TEST_PROBE_SERVICE_ID = 4,
    MICROS_PM_TEST_SERVICE_COUNT = 4,
    MICROS_PM_TEST_PROBE_PROFILE_ID = 8,
    MICROS_PM_TEST_RESERVED_PROCESS_SLOT = 4,
};

#define MICROS_PM_TEST_READY_TIMEOUT \
    UINT64_C(0x0000000005f5e100)
#define MICROS_PM_TEST_SCHEDULER_INTERVAL \
    UINT64_C(0x00000000000186a0)
#define MICROS_PM_TEST_REPORT_MAGIC \
    UINT64_C(0x504d534552564943)

#endif
