#ifndef MICROS_TESTS_QEMU_TTY_HANDOFF_PROTOCOL_H
#define MICROS_TESTS_QEMU_TTY_HANDOFF_PROTOCOL_H

enum {
    MICROS_TTY_HANDOFF_TEST_LAUNCHER_SERVICE_ID = 1,
    MICROS_TTY_HANDOFF_TEST_VM_SERVICE_ID = 2,
    MICROS_TTY_HANDOFF_TEST_PM_SERVICE_ID = 3,
    MICROS_TTY_HANDOFF_TEST_SERVICE_COUNT = 4,
};

#endif
