#ifndef MICROS_TESTS_QEMU_TTY_HANDOFF_PROTOCOL_H
#define MICROS_TESTS_QEMU_TTY_HANDOFF_PROTOCOL_H

#include <stdint.h>

enum {
    MICROS_TTY_HANDOFF_TEST_LAUNCHER_SERVICE_ID = 1,
    MICROS_TTY_HANDOFF_TEST_VM_SERVICE_ID = 2,
    MICROS_TTY_HANDOFF_TEST_PM_SERVICE_ID = 3,
    MICROS_TTY_HANDOFF_TEST_TTY_SERVICE_ID = 4,
    MICROS_TTY_HANDOFF_TEST_VFS_SERVICE_ID = 5,
    MICROS_TTY_HANDOFF_TEST_SERVICE_COUNT = 5,
    MICROS_TTY_HANDOFF_TEST_READ_COUNT = 17,
};

#define MICROS_TTY_HANDOFF_TEST_READY_TIMEOUT \
    UINT64_C(0x0000000005f5e100)
#define MICROS_TTY_HANDOFF_TEST_REPORT_MAGIC \
    UINT64_C(0x54545951454d5554)
#define MICROS_TTY_HANDOFF_TEST_INPUT_TRIGGER \
    "MICROS_TTY_INPUT_READY\n"
#define MICROS_TTY_HANDOFF_TEST_HOST_INPUT \
    "micros-ttyx\x7f-input\r"
#define MICROS_TTY_HANDOFF_TEST_EXPECTED_INPUT \
    "micros-tty-input\n"
#define MICROS_TTY_HANDOFF_TEST_PASS \
    "MICROS_TTY_TEST_PASS " \
    "handoff=two-phase mapping=exact irq=deferred " \
    "input=canonical output=interrupt-driven grants=checked\n"

#endif
