#ifndef MICROS_TESTS_QEMU_USER_RUNTIME_PROTOCOL_H
#define MICROS_TESTS_QEMU_USER_RUNTIME_PROTOCOL_H

#include <stdint.h>

#include "micros/endpoint.h"

#define MICROS_USER_RUNTIME_TEST_VERSION UINT64_C(0x0000000000000001)
#define MICROS_USER_RUNTIME_TEST_NOTIFY_MASK \
    UINT64_C(0x0123456789abcdef)
#define MICROS_USER_RUNTIME_TEST_DATA_SENTINEL \
    UINT64_C(0x8877665544332211)
#define MICROS_USER_RUNTIME_TEST_RODATA_SENTINEL \
    UINT64_C(0x1122334455667788)
#define MICROS_USER_RUNTIME_TEST_CANARY_BEFORE \
    UINT64_C(0x13579bdf2468ace0)
#define MICROS_USER_RUNTIME_TEST_CANARY_AFTER \
    UINT64_C(0xfedcba9876543210)

enum micros_user_runtime_test_role {
    MICROS_USER_RUNTIME_TEST_ROLE_NONE = 0,
    MICROS_USER_RUNTIME_TEST_ROLE_CLIENT = 1,
    MICROS_USER_RUNTIME_TEST_ROLE_SERVER = 2,
    MICROS_USER_RUNTIME_TEST_ROLE_PEER = 3,
};

enum micros_user_runtime_test_message_type {
    MICROS_USER_RUNTIME_TEST_MESSAGE_INITIAL = 0x1001,
    MICROS_USER_RUNTIME_TEST_MESSAGE_CALL_ONE = 0x1002,
    MICROS_USER_RUNTIME_TEST_MESSAGE_CALL_ONE_REPLY = 0x1003,
    MICROS_USER_RUNTIME_TEST_MESSAGE_CALL_TWO = 0x1004,
    MICROS_USER_RUNTIME_TEST_MESSAGE_CALL_TWO_REPLY = 0x1005,
    MICROS_USER_RUNTIME_TEST_MESSAGE_PEER_WAKE = 0x1006,
    MICROS_USER_RUNTIME_TEST_MESSAGE_GRANTS = 0x1007,
    MICROS_USER_RUNTIME_TEST_MESSAGE_COPY_DONE = 0x1008,
    MICROS_USER_RUNTIME_TEST_MESSAGE_RETRY = 0x1009,
    MICROS_USER_RUNTIME_TEST_MESSAGE_STALE_DONE = 0x100a,
    MICROS_USER_RUNTIME_TEST_MESSAGE_CLIENT_DONE = 0x100b,
};

enum micros_user_runtime_test_status {
    MICROS_USER_RUNTIME_TEST_STATUS_STARTUP = UINT64_C(1) << 0,
    MICROS_USER_RUNTIME_TEST_STATUS_STACK = UINT64_C(1) << 1,
    MICROS_USER_RUNTIME_TEST_STATUS_MEMORY = UINT64_C(1) << 2,
    MICROS_USER_RUNTIME_TEST_STATUS_REGISTERS = UINT64_C(1) << 3,
    MICROS_USER_RUNTIME_TEST_STATUS_IPC = UINT64_C(1) << 4,
    MICROS_USER_RUNTIME_TEST_STATUS_GRANTS = UINT64_C(1) << 5,
    MICROS_USER_RUNTIME_TEST_STATUS_COMPLETE = UINT64_C(1) << 6,
};

struct micros_user_runtime_test_config {
    uint64_t version;
    uint64_t role;
    micros_endpoint_t client_endpoint;
    micros_endpoint_t server_endpoint;
    micros_endpoint_t peer_endpoint;
    uint32_t reserved;
    uint64_t status;
    uint64_t failure;
};

_Static_assert(
    sizeof(struct micros_user_runtime_test_config) == 48,
    "user runtime test configuration layout changed"
);

#endif
