#ifndef MICROS_TESTS_QEMU_VFS_SERVICE_PROTOCOL_H
#define MICROS_TESTS_QEMU_VFS_SERVICE_PROTOCOL_H

#include <stdint.h>

enum {
    MICROS_VFS_TEST_LAUNCHER_SERVICE_ID = 1,
    MICROS_VFS_TEST_VM_SERVICE_ID = 2,
    MICROS_VFS_TEST_PM_SERVICE_ID = 3,
    MICROS_VFS_TEST_TTY_SERVICE_ID = 4,
    MICROS_VFS_TEST_RAMFS_SERVICE_ID = 5,
    MICROS_VFS_TEST_VFS_SERVICE_ID = 6,
    MICROS_VFS_TEST_APPLICATION_SERVICE_ID = 7,
    MICROS_VFS_TEST_SERVICE_COUNT = 7,
    MICROS_VFS_TEST_APPLICATION_IMAGE_ID = 107,
    MICROS_VFS_TEST_APPLICATION_PROCESS_SLOT = 6,
    MICROS_VFS_TEST_APPLICATION_PROFILE_ID = 8,
    MICROS_VFS_TEST_APPLICATION_RESIDENT_PAGE_LIMIT = 16,
};

#define MICROS_VFS_TEST_READY_TIMEOUT \
    UINT64_C(0x0000000011e1a300)
#define MICROS_VFS_TEST_MESSAGE_DRAIN UINT32_C(0x0004ff01)
#define MICROS_VFS_TEST_REPORT_MAGIC \
    UINT64_C(0x5646535445535401)
#define MICROS_VFS_TEST_FAILURE_CONFIGURATION \
    UINT64_C(0x56465354455354f1)
#define MICROS_VFS_TEST_FAILURE_READY \
    UINT64_C(0x56465354455354f2)
#define MICROS_VFS_TEST_FAILURE_FILESYSTEM \
    UINT64_C(0x56465354455354f3)
#define MICROS_VFS_TEST_FAILURE_DIRECTORY \
    UINT64_C(0x56465354455354f4)
#define MICROS_VFS_TEST_FAILURE_CONSOLE \
    UINT64_C(0x56465354455354f5)
#define MICROS_VFS_TEST_FAILURE_DRAIN \
    UINT64_C(0x56465354455354f6)

#define MICROS_VFS_TEST_MOTD "micros ramfs\n"
#define MICROS_VFS_TEST_NOTE_DATA "vfs note\n"
#define MICROS_VFS_TEST_INPUT_TRIGGER \
    "MICROS_VFS_TEST_INPUT_READY\n"
#define MICROS_VFS_TEST_HOST_INPUT \
    "micros-vfsx\x7f-input\r"
#define MICROS_VFS_TEST_EXPECTED_INPUT \
    "micros-vfs-input\n"
#define MICROS_VFS_TEST_PASS \
    "MICROS_VFS_TEST_PASS mount=single descriptors=owned " \
    "paths=absolute,relative files=two-hop directories=translated " \
    "console=two-hop grants=balanced\n"

#endif
