#ifndef MICROS_ARCH_RISCV64_TRAP_CONTEXT_H
#define MICROS_ARCH_RISCV64_TRAP_CONTEXT_H

#define MICROS_TRAP_CONTEXT_RA_OFFSET 0
#define MICROS_TRAP_CONTEXT_SP_OFFSET 8
#define MICROS_TRAP_CONTEXT_GP_OFFSET 16
#define MICROS_TRAP_CONTEXT_TP_OFFSET 24
#define MICROS_TRAP_CONTEXT_T0_OFFSET 32
#define MICROS_TRAP_CONTEXT_T1_OFFSET 40
#define MICROS_TRAP_CONTEXT_T2_OFFSET 48
#define MICROS_TRAP_CONTEXT_S0_OFFSET 56
#define MICROS_TRAP_CONTEXT_S1_OFFSET 64
#define MICROS_TRAP_CONTEXT_A0_OFFSET 72
#define MICROS_TRAP_CONTEXT_A1_OFFSET 80
#define MICROS_TRAP_CONTEXT_A2_OFFSET 88
#define MICROS_TRAP_CONTEXT_A3_OFFSET 96
#define MICROS_TRAP_CONTEXT_A4_OFFSET 104
#define MICROS_TRAP_CONTEXT_A5_OFFSET 112
#define MICROS_TRAP_CONTEXT_A6_OFFSET 120
#define MICROS_TRAP_CONTEXT_A7_OFFSET 128
#define MICROS_TRAP_CONTEXT_S2_OFFSET 136
#define MICROS_TRAP_CONTEXT_S3_OFFSET 144
#define MICROS_TRAP_CONTEXT_S4_OFFSET 152
#define MICROS_TRAP_CONTEXT_S5_OFFSET 160
#define MICROS_TRAP_CONTEXT_S6_OFFSET 168
#define MICROS_TRAP_CONTEXT_S7_OFFSET 176
#define MICROS_TRAP_CONTEXT_S8_OFFSET 184
#define MICROS_TRAP_CONTEXT_S9_OFFSET 192
#define MICROS_TRAP_CONTEXT_S10_OFFSET 200
#define MICROS_TRAP_CONTEXT_S11_OFFSET 208
#define MICROS_TRAP_CONTEXT_T3_OFFSET 216
#define MICROS_TRAP_CONTEXT_T4_OFFSET 224
#define MICROS_TRAP_CONTEXT_T5_OFFSET 232
#define MICROS_TRAP_CONTEXT_T6_OFFSET 240
#define MICROS_TRAP_CONTEXT_SSTATUS_OFFSET 248
#define MICROS_TRAP_CONTEXT_SEPC_OFFSET 256
#define MICROS_TRAP_CONTEXT_SCAUSE_OFFSET 264
#define MICROS_TRAP_CONTEXT_STVAL_OFFSET 272
#define MICROS_TRAP_CONTEXT_HART_CONTEXT_OFFSET 280
#define MICROS_TRAP_CONTEXT_SIZE 288

#define MICROS_HART_TRAP_PRIMARY_TOP_OFFSET 0
#define MICROS_HART_TRAP_PRIMARY_BOTTOM_OFFSET 8
#define MICROS_HART_TRAP_EMERGENCY_TOP_OFFSET 16
#define MICROS_HART_TRAP_EMERGENCY_BOTTOM_OFFSET 24
#define MICROS_HART_TRAP_ENTRY_T0_OFFSET 32
#define MICROS_HART_TRAP_ENTRY_T1_OFFSET 40
#define MICROS_HART_TRAP_ENTRY_T2_OFFSET 48
#define MICROS_HART_TRAP_ANCHOR_SIZE 56

#define MICROS_RISCV_SSTATUS_SIE (1 << 1)
#define MICROS_RISCV_SSTATUS_SPIE (1 << 5)
#define MICROS_RISCV_SSTATUS_SPP (1 << 8)
#define MICROS_RISCV_SSTATUS_SUM (1 << 18)

#ifndef __ASSEMBLER__

#include <stddef.h>
#include <stdint.h>

#include "micros/kernel_objects.h"
#include "micros/user_context.h"

struct micros_trap_frame {
    uint64_t ra;
    uint64_t sp;
    uint64_t gp;
    uint64_t tp;
    uint64_t t0;
    uint64_t t1;
    uint64_t t2;
    uint64_t s0;
    uint64_t s1;
    uint64_t a0;
    uint64_t a1;
    uint64_t a2;
    uint64_t a3;
    uint64_t a4;
    uint64_t a5;
    uint64_t a6;
    uint64_t a7;
    uint64_t s2;
    uint64_t s3;
    uint64_t s4;
    uint64_t s5;
    uint64_t s6;
    uint64_t s7;
    uint64_t s8;
    uint64_t s9;
    uint64_t s10;
    uint64_t s11;
    uint64_t t3;
    uint64_t t4;
    uint64_t t5;
    uint64_t t6;
    uint64_t sstatus;
    uint64_t sepc;
    uint64_t scause;
    uint64_t stval;
    uint64_t hart_context;
};

#define MICROS_TRAP_ASSERT_OFFSET(field, offset) \
    _Static_assert( \
        offsetof(struct micros_trap_frame, field) == (offset), \
        "trap " #field " offset mismatch" \
    )

MICROS_TRAP_ASSERT_OFFSET(ra, MICROS_TRAP_CONTEXT_RA_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(sp, MICROS_TRAP_CONTEXT_SP_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(gp, MICROS_TRAP_CONTEXT_GP_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(tp, MICROS_TRAP_CONTEXT_TP_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(t0, MICROS_TRAP_CONTEXT_T0_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(t1, MICROS_TRAP_CONTEXT_T1_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(t2, MICROS_TRAP_CONTEXT_T2_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(s0, MICROS_TRAP_CONTEXT_S0_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(s1, MICROS_TRAP_CONTEXT_S1_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(a0, MICROS_TRAP_CONTEXT_A0_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(a1, MICROS_TRAP_CONTEXT_A1_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(a2, MICROS_TRAP_CONTEXT_A2_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(a3, MICROS_TRAP_CONTEXT_A3_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(a4, MICROS_TRAP_CONTEXT_A4_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(a5, MICROS_TRAP_CONTEXT_A5_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(a6, MICROS_TRAP_CONTEXT_A6_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(a7, MICROS_TRAP_CONTEXT_A7_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(s2, MICROS_TRAP_CONTEXT_S2_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(s3, MICROS_TRAP_CONTEXT_S3_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(s4, MICROS_TRAP_CONTEXT_S4_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(s5, MICROS_TRAP_CONTEXT_S5_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(s6, MICROS_TRAP_CONTEXT_S6_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(s7, MICROS_TRAP_CONTEXT_S7_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(s8, MICROS_TRAP_CONTEXT_S8_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(s9, MICROS_TRAP_CONTEXT_S9_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(s10, MICROS_TRAP_CONTEXT_S10_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(s11, MICROS_TRAP_CONTEXT_S11_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(t3, MICROS_TRAP_CONTEXT_T3_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(t4, MICROS_TRAP_CONTEXT_T4_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(t5, MICROS_TRAP_CONTEXT_T5_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(t6, MICROS_TRAP_CONTEXT_T6_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(
    sstatus,
    MICROS_TRAP_CONTEXT_SSTATUS_OFFSET
);
MICROS_TRAP_ASSERT_OFFSET(sepc, MICROS_TRAP_CONTEXT_SEPC_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(scause, MICROS_TRAP_CONTEXT_SCAUSE_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(stval, MICROS_TRAP_CONTEXT_STVAL_OFFSET);
MICROS_TRAP_ASSERT_OFFSET(
    hart_context,
    MICROS_TRAP_CONTEXT_HART_CONTEXT_OFFSET
);

_Static_assert(
    sizeof(struct micros_trap_frame) == MICROS_TRAP_CONTEXT_SIZE,
    "trap context size mismatch"
);
_Static_assert(
    offsetof(struct micros_user_context, sstatus)
        == MICROS_TRAP_CONTEXT_SSTATUS_OFFSET,
    "user and trap sstatus offsets must match"
);
_Static_assert(
    offsetof(struct micros_user_context, sepc)
        == MICROS_TRAP_CONTEXT_SEPC_OFFSET,
    "user and trap sepc offsets must match"
);

#define MICROS_HART_TRAP_ASSERT_OFFSET(field, offset) \
    _Static_assert( \
        offsetof(struct micros_hart_trap_anchor, field) == (offset), \
        "hart trap " #field " offset mismatch" \
    )

MICROS_HART_TRAP_ASSERT_OFFSET(
    primary_stack_top,
    MICROS_HART_TRAP_PRIMARY_TOP_OFFSET
);
MICROS_HART_TRAP_ASSERT_OFFSET(
    primary_stack_bottom,
    MICROS_HART_TRAP_PRIMARY_BOTTOM_OFFSET
);
MICROS_HART_TRAP_ASSERT_OFFSET(
    emergency_stack_top,
    MICROS_HART_TRAP_EMERGENCY_TOP_OFFSET
);
MICROS_HART_TRAP_ASSERT_OFFSET(
    emergency_stack_bottom,
    MICROS_HART_TRAP_EMERGENCY_BOTTOM_OFFSET
);
MICROS_HART_TRAP_ASSERT_OFFSET(
    entry_t0,
    MICROS_HART_TRAP_ENTRY_T0_OFFSET
);
MICROS_HART_TRAP_ASSERT_OFFSET(
    entry_t1,
    MICROS_HART_TRAP_ENTRY_T1_OFFSET
);
MICROS_HART_TRAP_ASSERT_OFFSET(
    entry_t2,
    MICROS_HART_TRAP_ENTRY_T2_OFFSET
);

_Static_assert(
    sizeof(struct micros_hart_trap_anchor)
        == MICROS_HART_TRAP_ANCHOR_SIZE,
    "hart trap anchor size mismatch"
);
_Static_assert(
    offsetof(struct micros_hart, trap) == 0,
    "hart trap anchor must be the first hart field"
);

#undef MICROS_TRAP_ASSERT_OFFSET
#undef MICROS_HART_TRAP_ASSERT_OFFSET

#endif

#endif
